site_name: Knowledge Base

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  plugins:
    - search
  markdown_extensions:
    -admonition
    -pymdownx.details
    -pymdownx.superfences
