site_name: My Docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
  plugins:
    - search
