site_name: Meghann's Technical Writing Portfolio

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
plugins:
  - search
  - mkdocs-video:
      mark: "emb-video"
      css_style:
        width: "60%"
        height: "22.172vw"

markdown_extensions:
  - toc:
      permalink: True
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - pymdownx.superfences
